<a href="https://colab.research.google.com/github/BrianKvin/ds-ml-notebooks/blob/main/notebooks/exploratory/python_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Python for data science - A guide by Derek Banas

In [3]:
# Clear all variable values previously set
# from IPython import get_ipython
# get_ipython().magic('reset -sf')

In [5]:
# Provide ways to work with large multidimensional arrays
import numpy as np
# Allows for further data manipulation and analysis
import pandas as pd

from pandas_datareader import data as web # Reads stock data
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

import warnings
warnings.simplefilter("ignore")

In [6]:
# Constants
# Define path to files
PATH = 'https://github.com/derekbanas/Python4Finance'

In [8]:
# Numpy crush course
# make a numpy array
x = [1,2,3,4,5]
npa1 = np.array(x)
npa1

array([1, 2, 3, 4, 5])

In [10]:
# Create array in range
# create array from 0 to 4
npa2 = np.arange(0,5)
npa2

array([0, 1, 2, 3, 4])

In [11]:
# Define a step
npa3 = np.arange(0,11,2)
npa3

array([ 0,  2,  4,  6,  8, 10])