<a href="https://colab.research.google.com/github/BrianKvin/ds-ml-notebooks/blob/main/notebooks/exploratory/python_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Python for data science - A guide by Derek Banas

In [3]:
# Clear all variable values previously set
# from IPython import get_ipython
# get_ipython().magic('reset -sf')

In [5]:
# Provide ways to work with large multidimensional arrays
import numpy as np
# Allows for further data manipulation and analysis
import pandas as pd

from pandas_datareader import data as web # Reads stock data
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

import warnings
warnings.simplefilter("ignore")

In [6]:
# Constants
# Define path to files
PATH = 'https://github.com/derekbanas/Python4Finance'

In [8]:
# Numpy crush course
# make a numpy array
x = [1,2,3,4,5]
npa1 = np.array(x)
npa1

array([1, 2, 3, 4, 5])

In [10]:
# Create array in range
# create array from 0 to 4
npa2 = np.arange(0,5)
npa2

array([0, 1, 2, 3, 4])

In [11]:
# Define a step
npa3 = np.arange(0,11,2)
npa3

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# Matrices
# create a 4 row matrix with 3 columns with all having a value of 1
mat1 = np.ones((4,3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# create a 4 row matrix with 3 columns with all having a value of 0
mat2 = np.zeros((4,3))
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Random Matrices
# Random values between 0 and 50 as a matrix with 4 rows and 3 columns
mat3 = np.random.randint(0,50,(3,4))
mat3

array([[39, 12, 33, 25],
       [43,  2, 30, 39],
       [34, 33, 26, 28]])

In [21]:
# Generate Defined number of values in range
# Generate 10 equally distanced values between 1 and 10
mat4 = np.linspace(0,10,10)
mat4

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
# Reshape Arrays
# create an array with 12 values
mat4 = np.random.randint(0,50,12)
mat4

array([16, 29, 12, 22,  2, 42, 19, 36, 40, 16, 12, 20])

In [25]:
# Reshape to a 3 row 4 column array
mat5 = mat4.reshape(3,4)
mat5

array([[16, 29, 12, 22],
       [ 2, 42, 19, 36],
       [40, 16, 12, 20]])

In [26]:
# Reshape into a 3D array with 3 blocks, 2 rows, 2 columns
mat6 = mat5.reshape(3,2,2)
mat6

array([[[16, 29],
        [12, 22]],

       [[ 2, 42],
        [19, 36]],

       [[40, 16],
        [12, 20]]])

In [27]:
# Reshape into a 3D array with 2 blocks, 3 rows, and 2 columns
mat7 = mat5.reshape(2,3,2)
mat7

array([[[16, 29],
        [12, 22],
        [ 2, 42]],

       [[19, 36],
        [40, 16],
        [12, 20]]])

In [30]:
# Get the value in the 2nd block, 3rd row and, 1st column
mat7[1,2,1]

np.int64(20)

In [32]:
# Filter Arrays
# provide a boolean array where values are above 20
print(mat5)
mat5 > 20

[[16 29 12 22]
 [ 2 42 19 36]
 [40 16 12 20]]


array([[False,  True, False,  True],
       [False,  True, False,  True],
       [ True, False, False, False]])

In [33]:
# Return an array with values over 20
mat5 < 20

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [False,  True,  True, False]])

In [ ]:
# Statistics operations

In [ ]:
# The Seed function